export enum TypeDef { 
    LETTER = "LETTER", 
    NUMBER = "NUMBER", 
    KEYWORD = "KEYWORD", 
    IDENTIFIER = "IDENTIFIER", 
    STRING = "STRING", 
    OPERATOR = "OPERATOR",  
    PUNCTUATION = "PUNCTUATION", 
    WHITESPACE = "WHITESPACE"
}